# application-local.yml (git ignore)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

aws:
  s3:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    bucket: ${BUCKET}
    region: ${REGION}
